/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-05-11 18:57:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainboot_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\"\r\n");
      out.write("\tcontent=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.79.0\">\r\n");
      out.write("<title>Signin Template Â· Bootstrap v5.0</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"/static/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("\tfont-size: 1.125rem;\r\n");
      out.write("\ttext-anchor: middle;\r\n");
      out.write("\t-webkit-user-select: none;\r\n");
      out.write("\t-moz-user-select: none;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("\t.bd-placeholder-img-lg {\r\n");
      out.write("\t\tfont-size: 3.5rem;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"/static/signin.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"text-center\">\r\n");
      out.write("<script>\r\n");
      out.write("\t//ë¡ê·¸ì¸ì ì ëíë ê²ì¬\r\n");
      out.write("    function Warning_check(){ \r\n");
      out.write("    \t  var id = '");
      out.print(session.getAttribute("vo"));
      out.write("';\r\n");
      out.write("          if(id == \"null\"){ \r\n");
      out.write("              alert(\"ë¡ê·¸ì¸ì´ íìí ìë¹ì¤ìëë¤. íìì´ ìëìë¼ë©´ íìê°ìí ì í¬ ì¨ë°¥ìë¹ì¤ë¥¼ ì´ì©ë¶íëë¦½ëë¤^^\"); \r\n");
      out.write("          }\r\n");
      out.write("          else{\r\n");
      out.write("             location.replace(\"/sumbab/mypage/noticePage\");\r\n");
      out.write("          }\r\n");
      out.write("    }   \r\n");
      out.write("\t//================================================================================\r\n");
      out.write("    function Pick_check(){ \r\n");
      out.write("        var id = '");
      out.print(session.getAttribute("vo"));
      out.write("';\r\n");
      out.write("        console.log(\"id\");\r\n");
      out.write("\r\n");
      out.write("         if(id==\"null\"){ \r\n");
      out.write("            alert(\"ë¡ê·¸ì¸ì´ íìí ìë¹ì¤ìëë¤. íìì´ ìëìë¼ë©´ íìê°ìí ì í¬ ì¨ë°¥ìë¹ì¤ë¥¼ ì´ì©ë¶íëë¦½ëë¤^^\"); \r\n");
      out.write("         }\r\n");
      out.write("         else{\r\n");
      out.write("            location.replace(\"/sumbab/Pick/pickMain\");\r\n");
      out.write("         }\r\n");
      out.write("   }   \r\n");
      out.write("    function Mypage_check(){ \r\n");
      out.write("        var id = '");
      out.print(session.getAttribute("vo"));
      out.write("';\r\n");
      out.write("        console.log(\"id\");\r\n");
      out.write("\r\n");
      out.write("         if(id==\"null\"){ \r\n");
      out.write("            alert(\"ë¡ê·¸ì¸ì´ íìí ìë¹ì¤ìëë¤. íìì´ ìëìë¼ë©´ íìê°ìí ì í¬ ì¨ë°¥ìë¹ì¤ë¥¼ ì´ì©ë¶íëë¦½ëë¤^^\"); \r\n");
      out.write("         }\r\n");
      out.write("         else{\r\n");
      out.write("            location.replace(\"/sumbab/mypage/mypageMain\");\r\n");
      out.write("         }\r\n");
      out.write("   }   \r\n");
      out.write("    function Logout_check(){ \r\n");
      out.write("        var id = '");
      out.print(session.getAttribute("vo"));
      out.write("';\r\n");
      out.write("        console.log(\"id\");\r\n");
      out.write("\r\n");
      out.write("         if(id==\"null\"){ \r\n");
      out.write("            alert(\"ë¡ê·¸ì¸ì´ íìí ìë¹ì¤ìëë¤. íìì´ ìëìë¼ë©´ íìê°ìí ì í¬ ì¨ë°¥ìë¹ì¤ë¥¼ ì´ì©ë¶íëë¦½ëë¤^^\"); \r\n");
      out.write("         }\r\n");
      out.write("         else{\r\n");
      out.write("            location.replace(\"/sumbab/login/logout\");\r\n");
      out.write("         }\r\n");
      out.write("   }      \r\n");
      out.write("</script>\r\n");
      out.write("\t<main class=\"form-signin\">\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\t<img class=\"mb-4\" src=\"/static/bootstrap-logo.svg\" alt=\"\" width=\"72\"\r\n");
      out.write("\t\t\theight=\"57\">\r\n");
      out.write("\t\t<h1 class=\"h3 mb-3 fw-normal\">ì¨ë°¥ê¼­ì§ ììíê¸°!</h1>\r\n");
      out.write("\t\t<input type=\"button\" id=\"button1\" class=\"form-control\"\r\n");
      out.write("\t\tonclick=\"Warning_check();\" value=\"ê³µì§\"  required autofocus> \r\n");
      out.write("\t\t<input type=\"button\" id=\"button2\" class=\"form-control\"\r\n");
      out.write("\t\tonclick=\"Pick_check();\" value=\"ë³´ê´í¨\" required autofocus> \r\n");
      out.write("\t\t<a href=\"/sumbab/login/login\">\r\n");
      out.write("\t\t<input type=\"button\" id=\"button3\" value=\"ë¡ê·¸ì¸\" required autofocus /></a>\r\n");
      out.write("\t\t<a href=\"/sumbab/memberjoin\">\r\n");
      out.write("\t\t<input type=\"button\" id=\"button4\" value=\"íìê°ì\" required autofocus /></a>\r\n");
      out.write("\t\t<input type=\"button\" id=\"button5\"\r\n");
      out.write("\t\t onclick=\"Mypage_check();\" value=\"ë§ì´íì´ì§\" required autofocus> \r\n");
      out.write("\t\t<input type=\"button\" id=\"button6\"\r\n");
      out.write("\t\t onclick=\"Logout_check();\" value=\"ë¡ê·¸ìì\" required autofocus> \r\n");
      out.write("\t\t<div class=\"checkbox mb-3\">\r\n");
      out.write("\t\t\t<label> \r\n");
      out.write("\t\t\t\të¹ì ì ì¤ë§í¸í  F&Bíì¸ë\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p class=\"mt-5 mb-3 text-muted\">&copy; 2021</p>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
